on: [push, pull_request]

name: Continuous integration

jobs:

  test:
    name: Test Suite
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Test
        run: |
          cd rust_l00001_two_sum
          cargo check
          cargo test --all
